import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# 1. Load Data
try:
    df = pd.read_csv('pko_data/pko_results.csv')
except FileNotFoundError:
    # Create empty dummy data if no results exist yet
    df = pd.DataFrame(columns=['Platform', 'Person', 'Company', 'Tier', 'Tense', 'URL', 'Text'])

# 2. Generate Statistics
total_mentions = len(df)
elite_count = len(df[df['Tier'].str.contains('Elite', case=False, na=False)])
select_count = len(df[df['Tier'].str.contains('Select', case=False, na=False)])
last_updated = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

# 3. Create Charts
# Chart 1: Mentions by Tier
if not df.empty:
    fig_tier = px.pie(df, names='Tier', title='Mentions by Partner Tier', hole=0.4)
    tier_chart_html = fig_tier.to_html(full_html=False, include_plotlyjs='cdn')
    
    # Chart 2: Top Companies
    top_companies = df['Company'].value_counts().head(10).reset_index()
    top_companies.columns = ['Company', 'Count']
    fig_company = px.bar(top_companies, x='Count', y='Company', orientation='h', title='Top Active Partners')
    company_chart_html = fig_company.to_html(full_html=False, include_plotlyjs=False)
else:
    tier_chart_html = "<p>No data yet.</p>"
    company_chart_html = "<p>No data yet.</p>"

# 4. Generate HTML Dashboard
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Databricks PKO Tracker</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background: #f4f6f8; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 20px; }}
        .stat-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }}
        .stat-value {{ font-size: 32px; font-weight: bold; color: #FF3621; }}
        .stat-label {{ color: #666; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; }}
        .charts-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }}
        .chart-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .data-table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; }}
        .data-table th, .data-table td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #eee; }}
        .data-table th {{ background: #f8f9fa; font-weight: 600; }}
        .footer {{ text-align: center; color: #888; margin-top: 40px; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Databricks Partner Kickoff Tracker</h1>
            <p>Monitoring Elite & Select Partner Activity for FY27/2026</p>
            <small>Last Updated: {last_updated}</small>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">{total_mentions}</div>
                <div class="stat-label">Total Mentions</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{elite_count}</div>
                <div class="stat-label">Elite Partners</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{select_count}</div>
                <div class="stat-label">Select Partners</div>
            </div>
        </div>

        <div class="charts-grid">
            <div class="chart-card">{tier_chart_html}</div>
            <div class="chart-card">{company_chart_html}</div>
        </div>

        <div class="chart-card">
            <h3>Latest Mentions</h3>
            {df.head(50).to_html(classes='data-table', index=False, escape=False)}
        </div>
        
        <div class="footer">
            Generated by PKO Crawler • <a href="https://github.com/YOUR_USERNAME/YOUR_REPO">View Source</a>
        </div>
    </div>
</body>
</html>
"""

# 5. Save Report
with open('pko_data/index.html', 'w') as f:
    f.write(html_content)

print("Dashboard generated at pko_data/index.html")
